<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"
>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.opencellsoft</groupId>
	<artifactId>opencell</artifactId>
	<packaging>pom</packaging>
	<version>17.0.0</version>
	<name>Opencell Parent Project</name>
	<modules>
		<module>wildfly-cache-scripts</module>
		<module>opencell-security</module>
		<module>opencell-model</module>
		<module>opencell-api-dto</module>
		<module>opencell-tmforum</module>
		<module>opencell-admin</module>
		<module>opencell-api</module>
		<module>opencell-client</module>
		<module>opencell-scripts</module>
		<module>opencell-custom-api</module>
	</modules>
	<properties>
		<!-- Env set to dev, so that profile dev would be the default and also
		env value is used in copy some files for a specific configuration (e.g.
		import.sql) -->
		<env>dev</env>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<version.pdfbox>3.0.2</version.pdfbox>
		<jackson.version>2.17.0</jackson.version> <!-- wildfly 33 -->
		<commons.io.version>2.16.1</commons.io.version>
		<java.version>21</java.version>
		<version.ingenico-connect-sdk>6.31.0</version.ingenico-connect-sdk>
		<version.worldline.onlinepayments-sdk>3.5.0</version.worldline.onlinepayments-sdk>
		<version.paypal-sdk>1.14.0</version.paypal-sdk>
		<version.keycloak>25.0.2</version.keycloak>
		<version.stripe-sdk>22.4.0</version.stripe-sdk>
		<version.sips-payment-sdk>1.4.0</version.sips-payment-sdk>
		<version.jasper>7.0.1</version.jasper>
		<dbtype>generic</dbtype>
		<version.avalara-sdk>22.11.0</version.avalara-sdk>
		<primefaces.version>14.0.2</primefaces.version>
		<swagger.version>2.2.22</swagger.version>
		<springfox.swagger.version>3.0.0</springfox.swagger.version>
		<swagger.ui.version>3.0.0</swagger.ui.version>
		<sonar.projectKey>opencell-core</sonar.projectKey>
		<sonar.organization>opencellsoft</sonar.organization>
		<sonar.moduleKey>${project.groupId}:${project.artifactId}</sonar.moduleKey>
		<sonar.host.url>https://sonarcloud.io</sonar.host.url>
		<!-- used to switch dialect between postgres and oracle -->
		<opencell.dialect>${opencell.dialect}</opencell.dialect>
	</properties>
	<scm>
		<connection>scm:git:https://git.assembla.com/meveo.git</connection>
		<url>https://git.assembla.com/meveo.git</url>
	</scm>
	<repositories>
		<!-- <repository> -->
		<!-- <id>jboss-repo</id> -->
		<!--
		<url>http://repository.jboss.org/nexus/content/groups/public-jboss/</url> -->
		<!-- </repository> -->
		<repository>
			<id>opencell-repo</id>
			<url>https://libs.opencellsoft.com/</url>
		</repository>
		<repository>
			<id>opencell-nexus</id>
			<url>https://nexus.int.opencell.work/repository/maven-snapshots/</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>opencast-public</id>
			<url>https://nexus.opencast.org/nexus/content/repositories/public/</url>
		</pluginRepository>
		<pluginRepository>
			<id>central-maven</id>
			<url>https://central.maven.org/maven2/</url>
		</pluginRepository>
	</pluginRepositories>
	<distributionManagement>
		<site>
			<id>internal.repo</id>
			<name>Temporary Staging Repository</name>
			<url>file://${project.groupId}</url>
		</site>
	</distributionManagement>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.wildfly.bom</groupId>
				<artifactId>wildfly-ee-with-tools</artifactId>
				<version>34.0.1.Final</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.wildfly</groupId>
				<artifactId>wildfly-ee</artifactId>
				<version>34.0.1.Final</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft.wildfly</groupId>
				<artifactId>wildfly-cache-scripts</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-api</artifactId>
				<version>${project.version}</version>
				<type>test-jar</type>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-api-dto</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-admin-ejbs</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-admin-web</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-model</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-tmforum</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-security</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-client</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-scripts</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.opencellsoft</groupId>
				<artifactId>opencell-custom-api</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-core</artifactId>
				<version>2.22.1</version>
				<!-- AKK not in modules -->
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-api</artifactId>
				<version>2.23.1</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>3.15.0</version>
				<!-- Use compile scope to avoid compilation error in Opencell
				Script, even if we add it to jboss-deployment-structure.xml -->
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-csv</artifactId>
				<version>1.11.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-vfs2</artifactId>
				<version>2.9.0</version>
				<exclusions>
					<exclusion>
						<artifactId>commons-logging</artifactId>
						<groupId>commons-logging</groupId>
					</exclusion>
					<exclusion>
						<groupId>org.apache.hadoop</groupId>
						<artifactId>hadoop-hdfs-client</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>commons-cli</groupId>
				<artifactId>commons-cli</artifactId>
				<version>1.9.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>commons-validator</groupId>
				<artifactId>commons-validator</artifactId>
				<version>1.9.0</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>commons-fileupload</groupId>
				<artifactId>commons-fileupload</artifactId>
				<version>1.5</version>
			</dependency>
			<!-- maybe: <dependency> <groupId>org.apache.commons</groupId>
			<artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
			<version>2.0.0-M2</version> </dependency> -->
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-compress</artifactId>
				<version>1.26.2</version>
			</dependency>
			<dependency>
				<groupId>org.beanio</groupId>
				<artifactId>beanio</artifactId>
				<version>2.1.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.velocity</groupId>
				<artifactId>velocity-engine-core</artifactId>
				<version>2.3</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.primefaces.extensions</groupId>
				<artifactId>primefaces-extensions</artifactId>
				<version>${primefaces.version}</version>
				<classifier>jakarta</classifier>
			</dependency>
			<dependency>
				<groupId>org.primefaces</groupId>
				<artifactId>primefaces</artifactId>
				<version>${primefaces.version}</version>
				<classifier>jakarta</classifier>
			</dependency>
			<dependency>
				<groupId>org.reflections</groupId>
				<artifactId>reflections</artifactId>
				<version>0.10.2</version>
			</dependency>
			<dependency>
				<groupId>org.reflections</groupId>
				<artifactId>reflections-maven</artifactId>
				<version>0.9.8</version>
			</dependency>
			<dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>2.12.1</version>                
            </dependency>
			<dependency>
				<groupId>commons-net</groupId>
				<artifactId>commons-net</artifactId>
				<version>3.11.1</version>
			</dependency>
			<dependency>
				<groupId>com.github.mwiede</groupId>
				<artifactId>jsch</artifactId>
				<version>0.2.18</version>
			</dependency>
			<dependency>
				<groupId>com.thoughtworks.xstream</groupId>
				<artifactId>xstream</artifactId>
				<version>1.4.20</version>
			</dependency>
			<dependency>
				<groupId>com.thoughtworks.xstream</groupId>
				<artifactId>xstream-hibernate</artifactId>
				<version>1.4.20</version>
			</dependency>
			<dependency>
				<groupId>org.apache.groovy</groupId>
				<artifactId>groovy</artifactId>
				<version>4.0.22</version>
			</dependency>
			<dependency>
				<groupId>net.sourceforge.jexcelapi</groupId>
				<artifactId>jxl</artifactId>
				<version>2.6.12</version>
			</dependency>
			<dependency>
				<groupId>org.jboss</groupId>
				<artifactId>jboss-vfs</artifactId>
				<version>3.3.2.Final</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.mozilla</groupId>
				<artifactId>rhino</artifactId>
				<version>1.7.15</version>
			</dependency>
			<dependency>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi</artifactId>
				<version>5.3.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-ooxml</artifactId>
				<version>5.3.0</version>
				<exclusions>
					<exclusion>
						<groupId>org.apache.commons</groupId>
						<artifactId>commons-compress</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports-fonts</artifactId>
				<version>${version.jasper}</version>
			</dependency>
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports</artifactId>
				<version>${version.jasper}</version>
			</dependency>
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports-groovy</artifactId>
				<version>${version.jasper}</version>
			</dependency>
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports-pdf</artifactId>
				<version>${version.jasper}</version>
			</dependency>
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports-jaxen</artifactId>
				<version>${version.jasper}</version>
			</dependency>
			<dependency>
				<groupId>joda-time</groupId>
				<artifactId>joda-time</artifactId>
				<version>2.12.7</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>xalan</groupId>
				<artifactId>xalan</artifactId>
				<version>2.7.3</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>jaxen</groupId>
				<artifactId>jaxen</artifactId>
				<version>2.0.0</version>
			</dependency>
			<dependency>
				<groupId>org.igniterealtime.smack</groupId>
				<artifactId>smack</artifactId>
				<version>3.2.1</version>
			</dependency>
			<dependency>
				<groupId>com.googlecode.json-simple</groupId>
				<artifactId>json-simple</artifactId>
				<version>1.1.1</version>
			</dependency>
			<dependency>
				<groupId>org.scannotation</groupId>
				<artifactId>scannotation</artifactId>
				<version>1.0.3</version>
			</dependency>
			<dependency>
				<groupId>org.omnifaces</groupId>
				<artifactId>omnifaces</artifactId>
				<version>4.4.1</version>
			</dependency>
			<!--			<dependency>-->
			<!--				<groupId>com.lapis.jsfexporter</groupId>-->
			<!--				<artifactId>jsf-exporter-core</artifactId>-->
			<!--				<version>1.0.3.Final</version>-->
			<!--			</dependency>-->
			<!--			<dependency>-->
			<!--				<groupId>com.lapis.jsfexporter</groupId>-->
			<!--				<artifactId>export-type-csv</artifactId>-->
			<!--				<version>1.0.3.Final</version>-->
			<!--			</dependency>-->
			<!--			<dependency>-->
			<!--				<groupId>com.lapis.jsfexporter</groupId>-->
			<!--				<artifactId>export-source-primefaces</artifactId>-->
			<!--				<version>1.0.3.Final</version>-->
			<!--			</dependency>-->

			<dependency>
				<groupId>com.fasterxml.jackson.dataformat</groupId>
				<artifactId>jackson-dataformat-csv</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.dataformat</groupId>
				<artifactId>jackson-dataformat-smile</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.dataformat</groupId>
				<artifactId>jackson-dataformat-cbor</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.module</groupId>
				<artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.module</groupId>
				<artifactId>jackson-module-parameter-names</artifactId>
				<version>${jackson.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.datatype</groupId>
				<artifactId>jackson-datatype-jsr310</artifactId>
				<version>${jackson.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.dataformat</groupId>
				<artifactId>jackson-dataformat-xml</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>software.amazon.awssdk</groupId>
				<artifactId>s3</artifactId>
				<version>2.26.24</version>
			</dependency>
			<dependency>
				<groupId>org.carlspring.cloud.aws</groupId>
				<artifactId>s3fs-nio</artifactId>
				<version>1.0.4</version>
			</dependency>
			<dependency>
				<groupId>org.apache.ant</groupId>
				<artifactId>ant</artifactId>
				<version>1.10.14</version>
			</dependency>
			<dependency>
				<groupId>com.esotericsoftware.yamlbeans</groupId>
				<artifactId>yamlbeans</artifactId>
				<version>1.17</version>
			</dependency>
			<dependency>
				<groupId>com.opencsv</groupId>
				<artifactId>opencsv</artifactId>
				<version>5.9</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml</groupId>
				<artifactId>classmate</artifactId>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-core</artifactId>
				<version>${version.keycloak}</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-authz-client</artifactId>
				<version>${version.keycloak}</version>
				<exclusions>
					<exclusion>
						<groupId>org.jboss.logging</groupId>
						<artifactId>jboss-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-admin-client</artifactId>
				<version>${version.keycloak}</version>
				<exclusions>
					<exclusion>
						<groupId>org.apache.httpcomponents</groupId>
						<artifactId>httpclient</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jboss.spec.javax.ws.rs</groupId>
						<artifactId>jboss-jaxrs-api_2.1_spec</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jboss.logging</groupId>
						<artifactId>jboss-logging</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jboss.resteasy</groupId>
						<artifactId>resteasy-client</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jboss.resteasy</groupId>
						<artifactId>resteasy-core-spi</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jboss.resteasy</groupId>
						<artifactId>resteasy-multipart-provider</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jboss.resteasy</groupId>
						<artifactId>resteasy-jaxb-provider</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jboss.resteasy</groupId>
						<artifactId>resteasy-jackson2-provider</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.iban4j</groupId>
				<artifactId>iban4j</artifactId>
				<version>3.2.9-RELEASE</version>
			</dependency>
			<dependency>
				<groupId>org.apache.pdfbox</groupId>
				<artifactId>pdfbox</artifactId>
				<version>${version.pdfbox}</version>
			</dependency>
			<dependency>
				<groupId>com.itextpdf</groupId>
				<artifactId>itextpdf</artifactId>
				<version>5.5.13.4</version>
			</dependency>
			<dependency>
				<groupId>com.singingbush</groupId>
				<artifactId>barcode4j</artifactId>
				<version>2.2.4</version>
			</dependency>
			<dependency>
				<groupId>com.github.spullara.mustache.java</groupId>
				<artifactId>compiler</artifactId>
				<version>0.9.14</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.httpcomponents</groupId>
				<artifactId>httpcore-nio</artifactId>
				<version>4.4.16</version>
				<!-- Use compile scope to avoid compilation error in Opencell
				Script, even if we add it to jboss-deployment-structure.xml -->
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.oltu.oauth2</groupId>
				<artifactId>org.apache.oltu.oauth2.client</artifactId>
				<version>1.0.2</version>
			</dependency>
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-jaxrs2-jakarta</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-core-jakarta</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-jaxrs2-servlet-initializer-jakarta</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-annotations-jakarta</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-models-jakarta</artifactId>
				<version>${swagger.version}</version>
			</dependency>

			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>${springfox.swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>${swagger.ui.version}</version>
			</dependency>
			<dependency>
				<groupId>io.openapitools.swagger</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>2.1.6</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.plugin</groupId>
				<artifactId>spring-plugin-core</artifactId>
				<version>3.0.0</version>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-core</artifactId>
				<version>5.3.20</version>
			</dependency>

			<dependency>
				<groupId>com.ibm.jsonata4java</groupId>
				<artifactId>JSONata4Java</artifactId>
				<version>2.5.0</version>
			</dependency>

			<dependency>
				<groupId>org.immutables</groupId>
				<artifactId>value</artifactId>
				<version>2.10.1</version>
			</dependency>
			<dependency>
				<groupId>org.yaml</groupId>
				<artifactId>snakeyaml</artifactId>
				<version>2.2</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.tika</groupId>
				<artifactId>tika-core</artifactId>
				<version>2.9.2</version>
			</dependency>
			<dependency>
				<groupId>org.jboss.resteasy</groupId>
				<artifactId>resteasy-core-spi</artifactId>
				<version>6.2.11.Final</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>jakarta.jws</groupId>
				<artifactId>jakarta.jws-api</artifactId>
				<version>3.0.0</version>
			</dependency>
			<dependency>
				<groupId>org.wildfly.core</groupId>
				<artifactId>wildfly-server</artifactId>
				<version>25.0.0.Final</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.jayway.jsonpath</groupId>
				<artifactId>json-path</artifactId>
				<version>2.9.0</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.persistence</groupId>
				<artifactId>org.eclipse.persistence.moxy</artifactId>
				<version>4.0.4</version>
			</dependency>
			<dependency>
				<groupId>com.github.mifmif</groupId>
				<artifactId>generex</artifactId>
				<version>1.0.2</version>
			</dependency>
			<dependency>
				<groupId>org.bouncycastle</groupId>
				<artifactId>bcprov-jdk18on</artifactId>
				<version>1.78.1</version>
			</dependency>
			<dependency>
				<groupId>com.github.javaparser</groupId>
				<artifactId>javaparser-core</artifactId>
				<version>3.26.1</version>
			</dependency>
			<dependency>
				<groupId>com.github.javaparser</groupId>
				<artifactId>javaparser-symbol-solver-core</artifactId>
				<version>3.26.1</version>
			</dependency>
			<dependency>
				<groupId>com.github.spotbugs</groupId>
				<artifactId>spotbugs-annotations</artifactId>
				<version>4.8.6</version>
			</dependency>

			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-pool2</artifactId>
				<version>2.11.1</version>
			</dependency>

			<dependency>
				<groupId>io.hypersistence</groupId>
				<artifactId>hypersistence-utils-hibernate-63</artifactId>
				<version>3.8.2</version>
			</dependency>
			<dependency>
				<groupId>io.micrometer</groupId>
				<artifactId>micrometer-core</artifactId>
				<version>1.12.4</version>
			</dependency>


			<!-- For testing -->
			<dependency>
				<groupId>org.jboss.shrinkwrap.resolver</groupId>
				<artifactId>shrinkwrap-resolver-api-maven</artifactId>
				<scope>test</scope>
				<version>3.3.0</version>
			</dependency>
			<dependency>
				<groupId>org.hsqldb</groupId>
				<artifactId>hsqldb</artifactId>
				<version>2.7.3</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.assertj</groupId>
				<artifactId>assertj-core</artifactId>
				<version>3.26.3</version>
				<scope>provided</scope>
				<!-- DO NOT SET as test scope as EJB module use
				@VisibleForTesting annotation -->
			</dependency>
			<dependency>
				<groupId>org.dbunit</groupId>
				<artifactId>dbunit</artifactId>
				<version>2.8.0</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>5.12.0</version>
				<scope>test</scope>
				<exclusions>
					<exclusion>
						<groupId>net.bytebuddy</groupId>
						<artifactId>byte-buddy</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-inline</artifactId>
				<version>5.2.0</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>net.bytebuddy</groupId>
				<artifactId>byte-buddy</artifactId>
				<version>1.14.18</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.javassist</groupId>
				<artifactId>javassist</artifactId>
				<version>3.30.2-GA</version>
			</dependency>
			<dependency>
				<groupId>com.sun.el</groupId>
				<artifactId>el-ri</artifactId>
				<version>3.0.4</version>
				<scope>test</scope>
			</dependency>
			<!-- SLF4J implementation -->
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-simple</artifactId>
				<version>2.0.16</version>
				<scope>test</scope>
			</dependency>

		</dependencies>
	</dependencyManagement>
	<dependencies>
		<!-- Needed for running tests (you may also use TestNG) -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest</artifactId>
			<version>3.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.sonarsource.scanner.maven</groupId>
					<artifactId>sonar-maven-plugin</artifactId>
					<version>4.0.0.4121</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>3.3.1</version>
					<executions>
						<execution>
							<id>attach-sources</id>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>3.8.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-antrun-plugin</artifactId>
					<version>3.1.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.3.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-site-plugin</artifactId>
					<version>3.12.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-project-info-reports-plugin</artifactId>
					<version>3.6.2</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>2.4</version>
					<configuration>
						<encoding>${project.build.sourceEncoding}</encoding>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-clean-plugin</artifactId>
					<version>3.4.0</version>
				</plugin>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.13.0</version>
					<configuration>
						<release>${java.version}</release>
						<useIncrementalCompilation>false</useIncrementalCompilation>
						<forceJavacCompilerUse>true</forceJavacCompilerUse>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.4.2</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>buildnumber-maven-plugin</artifactId>
					<version>3.2.0</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>build-helper-maven-plugin</artifactId>
					<version>3.6.0</version>
				</plugin>
				<plugin>
					<groupId>org.jboss.as.plugins</groupId>
					<artifactId>jboss-as-maven-plugin</artifactId>
					<version>7.9.Final</version> <!-- AKK is needed? -->
				</plugin>
				<plugin>
					<groupId>com.google.code.maven-replacer-plugin</groupId>
					<artifactId>maven-replacer-plugin</artifactId>
					<version>1.4.1</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>jaxb2-maven-plugin</artifactId>
					<version>1.6</version><!-- Andrius with this version
					 opencell-model module works. EJB module use a different - 3.1.0 version-->
				</plugin>
				<plugin>
					<groupId>com.google.code.maven-replacer-plugin</groupId>
					<artifactId>replacer</artifactId>
					<version>1.5.3</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>sql-maven-plugin</artifactId>
					<version>1.5</version>
				</plugin>
				<plugin>
					<groupId>org.liquibase</groupId>
					<artifactId>liquibase-maven-plugin</artifactId>
					<version>4.29.0</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>exec-maven-plugin</artifactId>
					<version>3.3.0</version>
				</plugin>
				<plugin>
					<groupId>com.webcohesion.enunciate</groupId>
					<artifactId>enunciate-maven-plugin</artifactId>
					<version>2.18.1</version>
				</plugin>
				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>aspectj-maven-plugin</artifactId>
										<versionRange>[1.0,)</versionRange>
										<goals>
											<goal>test-compile</goal>
											<goal>compile</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute />
									</action>
								</pluginExecution>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId> org.apache.maven.plugins
										</groupId>
										<artifactId> maven-install-plugin
										</artifactId>
										<versionRange> [2.5,)
										</versionRange>
										<goals>
											<goal>install-file</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute>
											<runOnIncremental>false</runOnIncremental>
										</execute>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<skipTests>false</skipTests>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-site-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-project-info-reports-plugin</artifactId>
			</plugin>
		</plugins>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh</artifactId>
				<version>3.5.3</version>
			</extension>
		</extensions>
	</build>
	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<tags>
						<tag>
							<name>lastModifiedVersion</name>
							<!-- tag for all places -->
							<placement>a</placement>
							<head>Last Modified Version:</head>
						</tag>
					</tags>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.owasp</groupId>
				<artifactId>dependency-check-maven</artifactId>
				<version>10.0.3</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>aggregate</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
		</plugins>
	</reporting>
	<profiles>
		<profile>
			<id>development</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<property>
					<name>env</name>
					<value>dev</value>
				</property>
			</activation>
			<properties>
				<!-- Properties for liquibase plugin. Can be passed from a
				command line: mvn -Ddb.schema=ten2 -->
				<db.driver>org.postgresql.Driver</db.driver>
				<db.url>jdbc:postgresql://localhost/meveo</db.url>
				<db.schema>public</db.schema>
				<db.username>meveo</db.username>
				<db.password>meveo</db.password>
				<opencell.dialect>postgresql.MeveoPostgreSQLDialect</opencell.dialect>
			</properties>
			<dependencies>
				<!-- Dependency for liquibase plugin -->
				<dependency>
					<groupId>org.postgresql</groupId>
					<artifactId>postgresql</artifactId>
					<version>42.7.3</version>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>org.liquibase.ext</groupId>
					<artifactId>liquibase-postgresql</artifactId>
					<version>4.28.0</version>
					<scope>provided</scope>
					<exclusions>
						<exclusion>
							<groupId>org.liquibase</groupId>
							<artifactId>liquibase-core</artifactId>
						</exclusion>
						<exclusion>
							<groupId>postgresql</groupId>
							<artifactId>postgresql</artifactId>
						</exclusion>
					</exclusions>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>dev-mysql</id>
			<activation>
				<property>
					<name>env</name>
					<value>dev-mysql</value>
				</property>
			</activation>
			<properties>
				<!-- Properties for liquibase plugin. Can be passed from a
				command line: mvn -Ddb.schema=ten2 -->
				<db.driver>org.mariadb.jdbc.Driver</db.driver>
				<db.url>jdbc:mariadb://localhost:3306/meveo</db.url>
				<db.username>root</db.username>
				<db.password></db.password>
				<opencell.dialect>mysql.MeveoMysqlSQLDialect</opencell.dialect>
			</properties>
			<dependencies>
				<!-- Dependency for liquibase plugin -->
				<dependency>
					<groupId>org.mariadb.jdbc</groupId>
					<artifactId>mariadb-java-client</artifactId>
					<version>3.4.1</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>integration</id>
			<activation>
				<property>
					<name>env</name>
					<value>integr</value>
				</property>
			</activation>
			<properties>
				<!-- Properties for liquibase plugin. Can be passed from a
				command line: mvn -Ddb.schema=ten2 -->
				<db.driver>org.postgresql.Driver</db.driver>
				<db.url>jdbc:postgresql://localhost/integrmeveo</db.url>
				<db.schema>public</db.schema>
				<db.username>integrmeveo</db.username>
				<db.password>integrmeveo</db.password>
				<opencell.dialect>postgresql.MeveoPostgreSQLDialect</opencell.dialect>
			</properties>
			<dependencies>
				<!-- Dependency for liquibase plugin -->
				<dependency>
					<groupId>org.postgresql</groupId>
					<artifactId>postgresql</artifactId>
					<version>42.7.3</version>
				</dependency>
				<dependency>
					<groupId>org.liquibase.ext</groupId>
					<artifactId>liquibase-postgresql</artifactId>
					<version>4.28.0</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>production</id>
			<activation>
				<property>
					<name>env</name>
					<value>prod</value>
				</property>
			</activation>
			<properties>
				<!-- Properties for liquibase plugin. Can be passed from a
				command line: mvn -Ddb.schema=ten2 -->
				<db.driver>org.postgresql.Driver</db.driver>
				<db.url>jdbc:postgresql://localhost/meveo</db.url>
				<db.schema>public</db.schema>
				<db.username>meveo</db.username>
				<db.password>meveo</db.password>
				<opencell.dialect>portgresql.MeveoPostgreSQLDialect</opencell.dialect>
			</properties>
			<dependencies>
				<!-- Dependency for liquibase plugin -->
				<dependency>
					<groupId>org.postgresql</groupId>
					<artifactId>postgresql</artifactId>
					<version>42.7.3</version>
				</dependency>
				<dependency>
					<groupId>org.liquibase.ext</groupId>
					<artifactId>liquibase-postgresql</artifactId>
					<version>4.28.0</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<!-- To create CSV of third party libs, Use the command : mvn
			license:aggregate-add-third-party -P create-license-list -->
			<id>create-license-list</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>license-maven-plugin</artifactId>
						<version>2.4.0</version>
						<configuration>
							<useMissingFile>true</useMissingFile>
							<!-- assuming that the file is in the same dir as
							the pom.xml -->
							<fileTemplate>${basedir}/license-as-csv.ftl</fileTemplate>
						</configuration>
						<executions>
							<execution>
								<id>first</id>
								<goals>
									<goal>aggregate-add-third-party</goal>
								</goals>
								<phase>generate-resources</phase>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<!-- dev for oracle -->
		<profile>
			<id>dev-oracle</id>
			<activation>
				<property>
					<name>env</name>
					<value>dev-oracle</value>
				</property>
			</activation>
			<properties>
				<!-- Properties for liquibase plugin. Can be passed from a
				command line: mvn -Ddb.schema=ten2 -->
				<db.driver>oracle.jdbc.OracleDriver</db.driver>
				<db.url>jdbc:oracle:thin:@//oracle_host:1521/XE</db.url>
				<db.username>opencell</db.username>
				<!-- A setup for oracle XE
				<db.url>jdbc:oracle:thin:@//localhost:1521/XE</db.url>
				<db.username>c##opencell</db.username>
				<db.password>opencell</db.password> -->
				<db.password>opencell</db.password>
				<opencell.dialect>oracle.MeveoOracleDialect</opencell.dialect>
			</properties>
			<dependencies>
				<!-- Dependency for liquibase plugin -->
				<!--
				https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc10 -->
				<dependency>
					<groupId>com.oracle.database.jdbc</groupId>
					<artifactId>ojdbc11</artifactId>
					<version>23.4.0.24.05</version>
				</dependency>
				<dependency>
					<groupId>org.liquibase.ext</groupId>
					<artifactId>liquibase-oracle</artifactId>
					<version>4.28.0</version>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
</project>