@full @ignore
Feature: Sub creation, Service Activation, Charging and invoicing - Subscription with pricePlan.ratedEL

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                                                                                 | title                                   | dto                        | api                                                                          | action         | statusCode | status  | errorCode | message | entity | expected |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-accountHierarchy.json              | Create AccountHierarchy                 |                            | /account/accountHierarchy                                                    | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-oneshot_1.json                     | Create one-shot 1                       | OneShotChargeTemplateDto   | /catalog/oneShotChargeTemplate/createOrUpdate                                | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-service_1.json                     | Create service - 1                      | ServiceTemplateDto         | /catalog/serviceTemplate/createOrUpdate                                      | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-offer_1.json                       | Create offer 1                          | OfferTemplateDto           | /catalog/offerTemplate/createOrUpdate                                        | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-pricePlan-oneshot-without-tax.json | Create priceplan one-shot - without tax | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                                            | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-subscription_1.json                | Create subscription - 1                 | SubscriptionDto            | /billing/subscription/createOrUpdate                                         | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/activate-service_1.json                   | Activate services                       | ActivateServicesRequestDto | /billing/subscription/activateServices                                       | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/find-supscription_1.json                  | Find subscription - 1                   |                            | /billing/subscription?subscriptionCode=RS_FULL_200_PP_RATED_EL_Enterprise    | GET            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/update-provider.json                      | Update provider                         | ProviderDto                | /provider                                                                    | Update         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-oneshot_2.json                     | Create one-shot 2                       | OneShotChargeTemplateDto   | /catalog/oneShotChargeTemplate/createOrUpdate                                | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-pricePlan-oneshot-with-tax.json    | Create priceplan one-shot - with tax    | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                                            | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-service_2.json                     | Create service - 2                      | ServiceTemplateDto         | /catalog/serviceTemplate/createOrUpdate                                      | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-offer_2.json                       | Create offer - 2                        | OfferTemplateDto           | /catalog/offerTemplate/createOrUpdate                                        | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/create-subscription_2.json                | Create subscription 2                   | SubscriptionDto            | /billing/subscription/createOrUpdate                                         | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/activate-service_2.json                   | Activate services - 2                   | ActivateServicesRequestDto | /billing/subscription/activateServices                                       | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/find-supscription_2.json                  | Find subscription - 2                   |                            | /billing/subscription?subscriptionCode=RS_FULL_200_PP_RATED_EL_NotEnterprise | GET            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/10-subscription-with-pricePlan.ratedEL/revert-provider.json                      | Revert provider                         | ProviderDto                | /provider                                                                    | Update         |        200 | SUCCESS |           |         |        |          |
