@full
Feature: Create BR and Invoicing with Reference Date

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                                                                                     | title                            | dto                        | api                                                                      | action         | statusCode | status  | errorCode | message | entity         | expected                                                                                                                                        |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/create-billingCycle.json              | Create BillingCycle              | BillingCycleDto            | /billingCycle/createOrUpdate                                             | CreateOrUpdate |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/create-billingAccount.json            | Create Billing Account           | BillingAccountDto          | /account/billingAccount/createOrUpdate                                   | CreateOrUpdate |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/create-userAccount-invoice.json       | Create User Account Invoice      | UserAccountDto             | /account/userAccount/createOrUpdate                                      | CreateOrUpdate |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/create-susbcription.json              | Create subscription              | SubscriptionDto            | /billing/subscription/createOrUpdate                                     | CreateOrUpdate |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/activate-service-on-subscription.json | Activate service on subscription | ActivateServicesRequestDto | /billing/subscription/activateServices                                   | POST           |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/create-BR.json                        | create BR                        | CreateBillingRunDto        | /billing/invoicing/createBillingRun                                      | POST           |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/recurring-rating-job.json             | Recurring Rating Job             |                            | /job/execute                                                             | POST           |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/rated-transaction-job.json            | Rated Transaction Job            |                            | /job/execute                                                             | POST           |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/invoicing-job_1.json                  | Invoicing Job                    |                            | /job/execute                                                             | POST           |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/vaidate-BR.json                       | validate BR                      |                            | /billing/invoicing/validateBillingRun                                    | POST           |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/invoicing-job_2.json                  | Invoicing Job 2                  |                            | /job/execute                                                             | POST           |        200 | SUCCESS |           |         |                |                                                                                                                                                 |
      | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/find_billingAccount.json              | find Billing Account             |                            | /account/billingAccount?billingAccountCode=RS_FULL_200_BA_Reference_Date | GET            |        200 | SUCCESS |           |         | billingAccount | scenarios/full/00003-sub-creation-service-activation-charging-invoicing/11-create-BR-and-invoicing-with-reference-date/find_billingAccount.json |