/*
* (C) Copyright 2009-2013 Manaty SARL (http://manaty.net/) and contributors.
*
* Licensed under the GNU Public Licence, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.gnu.org/licenses/gpl-2.0.txt
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.02 at 02:29:16 PM WET 
//

package org.meveo.model.jaxb.customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tradingCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tradingCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tradingLanguageCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;sequence>
 *         &lt;element ref="{}customers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {  "code",
		"tradingCurrencyCode",
		"tradingCountryCode",
		"tradingLanguageCode",
		"customers" })
@XmlRootElement(name = "seller")
public class Seller {

    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "tradingCurrencyCode")
    protected String tradingCurrencyCode;
    @XmlAttribute(name = "tradingCountryCode")
    protected String tradingCountryCode;
    @XmlAttribute(name = "tradingLanguageCode")
    protected String tradingLanguageCode;
    
    protected Customers customers;

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTradingCurrencyCode() {
		return tradingCurrencyCode;
	}

	public void setTradingCurrencyCode(String tradingCurrencyCode) {
		this.tradingCurrencyCode = tradingCurrencyCode;
	}

	public String getTradingCountryCode() {
		return tradingCountryCode;
	}

	public void setTradingCountryCode(String tradingCountryCode) {
		this.tradingCountryCode = tradingCountryCode;
	}

	public String getTradingLanguageCode() {
		return tradingLanguageCode;
	}

	public void setTradingLanguageCode(String tradingLanguageCode) {
		this.tradingLanguageCode = tradingLanguageCode;
	}

	public Customers getCustomers() {
		return customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

}
