<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.opencellsoft</groupId>
        <artifactId>opencell</artifactId>
        <version>17.0.0</version>
    </parent>
    <groupId>com.opencellsoft.wildfly</groupId>
    <artifactId>wildfly-cache-scripts</artifactId>
    <name>Cache scripts</name>
    <description>Infinispan cache manipulation functions</description>
    <dependencies>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-core-jakarta</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>jboss-logging</artifactId>
                    <groupId>org.jboss.logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>