@full04-multiple-charges-trigger
Feature: Rating - Discounts

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                              | title                                                       | dto                        | api                                         | action         | statusCode | status  | errorCode         | message                                                                                                                                 | entity | expected |
      | scenarios/full/00006-rating/03-discounts/create-discountPlan.json                                     | create DiscountPlan                                         | DiscountPlanDto            | /catalog/discountPlan/createOrUpdate        | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-missing-discount-type.json           | create DiscountPlanItem - missing discount type             | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        400 | FAIL    | MISSING_PARAMETER | The following parameters are required or contain invalid values: discountValue, discountValueEL or discountValueELSpark, discountValue. |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-missing-percent.json                 | create DiscountPlanItem - missing percent                   | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        400 | FAIL    | MISSING_PARAMETER | The following parameters are required or contain invalid values: discountValue, discountValueEL or discountValueELSpark, discountValue. |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountplanItem-missing-fixed.json                   | create DiscountPlanItem - missing fixed                     | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        400 | FAIL    | MISSING_PARAMETER | The following parameters are required or contain invalid values: discountValue, discountValueEL or discountValueELSpark, discountValue. |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-percentage-5.json                    | create DiscountPlanItem percentage 5                        | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-fix-5.json                           | create DiscountPlanItem fix 5                               | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlan-effective-date.json                      | create DiscountPlan - effective date                        | DiscountPlanDto            | /catalog/discountPlan/createOrUpdate        | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-fixed-10-effectivate-date.json       | create DiscountPlanItem fixed 10 - effectivity date         | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlan-invalid-effectivity-date.json            | create DiscountPlan - invalid effectivity date              | DiscountPlanDto            | /catalog/discountPlan/createOrUpdate        | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-fixed-15-invalid-effective-date.json | create DiscountPlanItem fixed 15 - invalid effectivity date | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discounPlan-with-duration.json                        | create DiscountPlan - with duration                         | DiscountPlanDto            | /catalog/discountPlan/createOrUpdate        | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-fixed-15-with-duration.json          | create DiscountPlanItem fixed 15 - with duration            | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlan_2.json                                   | create DiscountPlan 2                                       | DiscountPlanDto            | /catalog/discountPlan/createOrUpdate        | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-discountPlanItem-fixed-20.json                        | create DiscountPlanItem fixed 20                            | DiscountPlanItemDto        | /catalog/discountPlanItem/createOrUpdate    | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-billing-cycle.json                                    | Create billing cycle                                        | BillingCycleDto            | /billingCycle/createOrUpdate                | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-accountHierarchy.json                                 | Create AccountHierarchy                                     |                            | /account/accountHierarchy/createOrUpdate    | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-usage-charge.json                                     | Create usage charge                                         | UsageChargeTemplateDto     | /catalog/usageChargeTemplate/createOrUpdate | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-pricePlan.json                                        | Create priceplan                                            | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate           | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-service.json                                          | Create service                                              | ServiceTemplateDto         | /catalog/serviceTemplate/createOrUpdate     | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-offer.json                                            | Create offer                                                | OfferTemplateDto           | /catalog/offerTemplate/createOrUpdate       | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-subscription.json                                     | Create Subscription                                         | SubscriptionDto            | /billing/subscription/createOrUpdate        | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/activate-subscription.json                                   | Activate subscription                                       | String                     | /billing/subscription/activate              | POST           |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/activate-services.json                                       | Activate services                                           | ActivateServicesRequestDto | /billing/subscription/activateServices      | POST           |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-access.json                                           | Create access                                               | AccessDto                  | /account/access/createOrUpdate              | CreateOrUpdate |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/charge-cdr.json                                              | Charge CDR                                                  | String                     | /billing/mediation/chargeCdr                | POST           |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/run-rt.json                                                  | Run RT                                                      |                            | /job/execute                                | POST           |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/create-br.json                                               | Create BR                                                   | CreateBillingRunDto        | /billing/invoicing/createBillingRun         | Create         |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/invoicing-job.json                                           | Invoicing Job                                               |                            | /job/execute                                | POST           |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/validate-br.json                                             | Validate BR                                                 |                            | /billing/invoicing/validateBillingRun       | POST           |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
      | scenarios/full/00006-rating/03-discounts/xml-job.json                                                 | XML Job                                                     |                            | /job/execute                                | POST           |        200 | SUCCESS |                   |                                                                                                                                         |        |          |
