@full @ignore
Feature: Rating - Multiple Charges Trigger

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                            | title              | dto                        | api                                                         | action         | statusCode | status  | errorCode | message | entity | expected |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/CH1N.json                   | CH1N               | UsageChargeTemplateDto     | /catalog/usageChargeTemplate/createOrUpdate                 | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/CH2C100.json                | CH2C100            | UsageChargeTemplateDto     | /catalog/usageChargeTemplate/createOrUpdate                 | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/CH3C50.json                 | CH3C50             | UsageChargeTemplateDto     | /catalog/usageChargeTemplate/createOrUpdate                 | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/CH4N.json                   | CH4N               | UsageChargeTemplateDto     | /catalog/usageChargeTemplate/createOrUpdate                 | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/CH5.json                    | CH5                | UsageChargeTemplateDto     | /catalog/usageChargeTemplate/createOrUpdate                 | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/CH6.json                    | CH6                | UsageChargeTemplateDto     | /catalog/usageChargeTemplate/createOrUpdate                 | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/C100.json                   | C100               | CounterTemplateDto         | /catalog/counterTemplate/createOrUpdate                     | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/C50.json                    | C50                | CounterTemplateDto         | /catalog/counterTemplate/createOrUpdate                     | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/pricePlan_1.json            | Priceplan1         | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                           | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/pricePlan_2.json            | Priceplan2         | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                           | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/pricePlan_3.json            | Priceplan3         | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                           | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/pricePlan_4.json            | Priceplan4         | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                           | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/pricePlan_5.json            | Priceplan5         | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                           | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/pricePlan_6.json            | Priceplan6         | PricePlanMatrixDto         | /catalog/pricePlan/createOrUpdate                           | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/service.json                | Service            | ServiceTemplateDto         | /catalog/serviceTemplate/createOrUpdate                     | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/offer.json                  | Offer              | OfferTemplateDto           | /catalog/offerTemplate/createOrUpdate                       | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/userAccount_1.json          | UA                 | CRMAccountHierarchyDto     | /account/accountHierarchy/createOrUpdateCRMAccountHierarchy | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/subscription_1.json         | Subscription       | SubscriptionDto            | /billing/subscription/createOrUpdate                        | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/access_1.json               | Access             | AccessDto                  | /account/access/createOrUpdate                              | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/activate-services_1.json    | Activate services  | ActivateServicesRequestDto | /billing/subscription/activateServices                      | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/userAccount_2.json          | UserAccount2       | UserAccountDto             | /account/userAccount                                        | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/userAccount_3.json          | UserAccount3       | UserAccountDto             | /account/userAccount                                        | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/userAccount_4.json          | UserAccount4       | UserAccountDto             | /account/userAccount                                        | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/userAccount_5.json          | UserAccount5       | UserAccountDto             | /account/userAccount                                        | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/subscription_2.json         | S2                 | SubscriptionDto            | /billing/subscription/createOrUpdate                        | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/subscription_3.json         | S3                 | SubscriptionDto            | /billing/subscription/createOrUpdate                        | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/subscription_4.json         | S4                 | SubscriptionDto            | /billing/subscription/createOrUpdate                        | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/subscription_5.json         | S5                 | SubscriptionDto            | /billing/subscription/createOrUpdate                        | CreateOrUpdate |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/access_2.json               | A2                 | AccessDto                  | /account/access                                             | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/access_3.json               | A3                 | AccessDto                  | /account/access                                             | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/access_4.json               | A4                 | AccessDto                  | /account/access                                             | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/access_5.json               | A5                 | AccessDto                  | /account/access                                             | Create         |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/activate-services_2.json    | Activate services2 | ActivateServicesRequestDto | /billing/subscription/activateServices                      | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/activate-services_3.json    | Activate services3 | ActivateServicesRequestDto | /billing/subscription/activateServices                      | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/activate-services_4.json    | Activate services4 | ActivateServicesRequestDto | /billing/subscription/activateServices                      | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/activate-services_5.json    | Activate services5 | ActivateServicesRequestDto | /billing/subscription/activateServices                      | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/cdr_1.json                  | C1                 | String                     | /billing/mediation/chargeCdr                                | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/cdr_2.json                  | C2                 | String                     | /billing/mediation/chargeCdr                                | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/cdr_3.json                  | C3                 | String                     | /billing/mediation/chargeCdr                                | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/cdr_4.json                  | C4                 | String                     | /billing/mediation/chargeCdr                                | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/cdr_5.json                  | C5                 | String                     | /billing/mediation/chargeCdr                                | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/invoice-subscription_1.json | Invoice Sub1       |                            | /invoice/generateInvoice                                    | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/invoice-subscription_2.json | Invoice Sub2       |                            | /invoice/generateInvoice                                    | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/invoice-subscription_3.json | Invoice Sub3       |                            | /invoice/generateInvoice                                    | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/invoice-subscription_4.json | Invoice Sub4       |                            | /invoice/generateInvoice                                    | POST           |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00006-rating/04-multiple-charges-trigger/invoice-subscription_5.json | Invoice Sub5       |                            | /invoice/generateInvoice                                    | POST           |        200 | SUCCESS |           |         |        |          |
