@full
Feature: Rating - Recurring rating

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                                    | title                                                     | dto                                     | api                                                                                                                                                                                                 | action         | statusCode | status  | errorCode | message | entity           | expected                                                                                                    |
      | scenarios/full/00006-rating/01-recurring-rating/create-5-day-period-calendar.json                           | Create 5 day period calendar                              | CalendarDto                             | /calendar/createOrUpdate                                                                                                                                                                            | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-120-hours-period-calendar.json                       | Create 120 hours period calendar                          | CalendarDto                             | /calendar/createOrUpdate                                                                                                                                                                            | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-recurring-charge-5-days-apply-in-advance.json        | Create recurring charge - 5 days, apply in advance        | RecurringChargeTemplateDto              | /catalog/recurringChargeTemplate/createOrUpdate                                                                                                                                                     | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-recurring-charge-5-days-not-apply-in-advance.json    | Create recurring charge - 5 days, NOT apply in advance    | RecurringChargeTemplateDto              | /catalog/recurringChargeTemplate/createOrUpdate                                                                                                                                                     | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-recurring-charge-120-hours-apply-in-advance.json     | Create recurring charge - 120 hours, apply in advance     | RecurringChargeTemplateDto              | /catalog/recurringChargeTemplate/createOrUpdate                                                                                                                                                     | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-recurring-charge-120-hours-not-apply-in-advance.json | Create recurring charge - 120 hours, NOT apply in advance | RecurringChargeTemplateDto              | /catalog/recurringChargeTemplate/createOrUpdate                                                                                                                                                     | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-pp-for-5-days-in-advance.json                        | Create PP for 5 days in advance                           | PricePlanMatrixDto                      | /catalog/pricePlan/createOrUpdate                                                                                                                                                                   | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-pp-for-5-days-not-in-advance.json                    | Create PP for 5 days not in advance                       | PricePlanMatrixDto                      | /catalog/pricePlan/createOrUpdate                                                                                                                                                                   | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-pp-for-120-hours-in-advance.json                     | Create PP for 120 hours in advance                        | PricePlanMatrixDto                      | /catalog/pricePlan/createOrUpdate                                                                                                                                                                   | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-pp-for-120-hours-not-in-advance.json                 | Create PP for 120 hours not in advance                    | PricePlanMatrixDto                      | /catalog/pricePlan/createOrUpdate                                                                                                                                                                   | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-service.json                                         | Create service                                            | ServiceTemplateDto                      | /catalog/serviceTemplate/createOrUpdate                                                                                                                                                             | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-offer.json                                           | Create offer                                              | OfferTemplateDto                        | /catalog/offerTemplate/createOrUpdate                                                                                                                                                               | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-ua.json                                              | Create UA                                                 | CRMAccountHierarchyDto                  | /account/accountHierarchy/createOrUpdateCRMAccountHierarchy                                                                                                                                         | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/create-subscription.json                                    | Create subscription                                       | SubscriptionDto                         | /billing/subscription/createOrUpdate                                                                                                                                                                | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/activate-services.json                                      | Activate services                                         | ActivateServicesRequestDto              | /billing/subscription/activateServices                                                                                                                                                              | POST           |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations.json                                 | Find wallet operations                                    |                                         | /billing/wallet/operation/list?query=wallet.userAccount.code:RS_FULL_171_RECURRING&limit=50&sortBy=id&sortOrder=ASCENDING                                                                           | GET            |        200 | SUCCESS |           |         | walletOperations | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations.json                                 |
      | scenarios/full/00006-rating/01-recurring-rating/terminate-service.json                                      | Terminate service                                         | TerminateSubscriptionServicesRequestDto | /billing/subscription/terminateServices                                                                                                                                                             | POST           |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations-after-termination.json               | Find wallet operations after termination                  |                                         | /billing/wallet/operation/list?query=wallet.userAccount.code:RS_FULL_171_RECURRING&limit=50&offset=22&sortBy=id&sortOrder=ASCENDING                                                                 | GET            |        200 | SUCCESS |           |         | walletOperations | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations-after-termination.json               |
      | scenarios/full/00006-rating/01-recurring-rating/create-subscription-with-end-agreement-date.json            | Create subscription with end agreement date               | SubscriptionDto                         | /billing/subscription/createOrUpdate                                                                                                                                                                | CreateOrUpdate |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/activate-services-end-agreement.json                        | Activate services - end agreement                         | ActivateServicesRequestDto              | /billing/subscription/activateServices                                                                                                                                                              | POST           |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations-end-agreement.json                   | Find wallet operations - end agreement                    |                                         | /billing/wallet/operation/list?query=wallet.userAccount.code:RS_FULL_171_RECURRING\|chargeInstance.subscription.code:RS_FULL_171_SUB_RECURRING_END&limit=50&sortBy=id&sortOrder=ASCENDING           | GET            |        200 | SUCCESS |           |         | walletOperations | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations-end-agreement.json                   |
      | scenarios/full/00006-rating/01-recurring-rating/terminate-service-end-agreement.json                        | Terminate service - end agreement                         | TerminateSubscriptionServicesRequestDto | /billing/subscription/terminateServices                                                                                                                                                             | POST           |        200 | SUCCESS |           |         |                  |                                                                                                             |
      | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations-after-termination-end-agreement.json | Find wallet operations after termination - end agreement  |                                         | /billing/wallet/operation/list?query=wallet.userAccount.code:RS_FULL_171_RECURRING\|chargeInstance.subscription.code:RS_FULL_171_SUB_RECURRING_END&limit=50&offset=22&sortBy=id&sortOrder=ASCENDING | GET            |        200 | SUCCESS |           |         | walletOperations | scenarios/full/00006-rating/01-recurring-rating/find-wallet-operations-after-termination-end-agreement.json |
