package org.meveo.model.mediation;

public enum CDRRejectionCauseEnum {
    TECH_ERR, INVALID_FORMAT, DUPLICATE, ACCESS_NOT_FOUND, MULTIPLE_ACCESS, INVALID_ACCESS, ACCESS_INVALID_DATE, SUBSCRIPTION_NOT_ACTIVATED, SUBSCRIPTION_TERMINATED
}
