<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.opencellsoft</groupId>
		<artifactId>opencell</artifactId>
		<relativePath>../pom.xml</relativePath>
		<version>17.0.0</version>
	</parent>
	<artifactId>opencell-api</artifactId>
	<name>Opencell API</name>
	<properties>
		<swagger.server.link>http://localhost:8080/opencell/api/rest</swagger.server.link>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-compress</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-admin-ejbs</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-model</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-api-dto</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-tmforum</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft.wildfly</groupId>
			<artifactId>wildfly-cache-scripts</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.singingbush</groupId>
			<artifactId>barcode4j</artifactId>
		</dependency>
		<!-- Libraries included in JBoss -->
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.ejb</groupId>
			<artifactId>jakarta.ejb-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.interceptor</groupId>
			<artifactId>jakarta.interceptor-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-jaxb-provider</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-jackson2-provider</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-client</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-multipart-provider</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.github.javaparser</groupId>
			<artifactId>javaparser-symbol-solver-core</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.jms</groupId>
			<artifactId>jakarta.jms-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- End of libraries provided in Jboss -->
		<dependency>
			<groupId>org.hibernate.orm</groupId>
			<artifactId>hibernate-core</artifactId>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>org.jboss.logging</groupId>
					<artifactId>jboss-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.enterprise.concurrent</groupId>
			<artifactId>jakarta.enterprise.concurrent-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- End of libraries provided in Jboss -->
		<dependency>
			<groupId>org.iban4j</groupId>
			<artifactId>iban4j</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.shrinkwrap.resolver</groupId>
			<artifactId>shrinkwrap-resolver-api-maven</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-jakarta</artifactId>
			<!--			<exclusions>-->
			<!--				<exclusion>-->
			<!--					<groupId>com.fasterxml.jackson.jaxrs</groupId>-->
			<!--					<artifactId>jackson-jaxrs-json-provider</artifactId>-->
			<!--				</exclusion>-->
			<!--			</exclusions>-->
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-core-jakarta</artifactId>
			<!--			<exclusions>-->
			<!--				<exclusion>-->
			<!--					<groupId>org.yaml</groupId>-->
			<!--					<artifactId>snakeyaml</artifactId>-->
			<!--				</exclusion>-->
			<!--				<exclusion>-->
			<!--					<groupId>com.fasterxml.jackson.dataformat</groupId>-->
			<!--					<artifactId>jackson-dataformat-yaml</artifactId>-->
			<!--				</exclusion>-->
			<!--				<exclusion>-->
			<!--					<groupId>jakarta.activation</groupId>-->
			<!--					<artifactId>jakarta.activation-api</artifactId>-->
			<!--				</exclusion>-->
			<!--				<exclusion>-->
			<!--					<groupId>jakarta.xml.bind</groupId>-->
			<!--					<artifactId>jakarta.xml.bind-api</artifactId>-->
			<!--				</exclusion>-->
			<!--			</exclusions>-->
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-servlet-initializer-jakarta</artifactId>
		</dependency>
		<!--		<dependency>-->
		<!--			<groupId>io.springfox</groupId>-->
		<!--			<artifactId>springfox-swagger2</artifactId>-->
		<!--			<exclusions>-->
		<!--				<exclusion>-->
		<!--					<groupId>org.springframework</groupId>-->
		<!--					<artifactId>spring-core</artifactId>-->
		<!--				</exclusion>-->
		<!--				<exclusion>-->
		<!--					<groupId>net.bytebuddy</groupId>-->
		<!--					<artifactId>byte-buddy</artifactId>-->
		<!--				</exclusion>-->
		<!--			</exclusions>-->
		<!--		</dependency>-->
		<!--		<dependency>-->
		<!--			<groupId>org.springframework</groupId>-->
		<!--			<artifactId>spring-core</artifactId>-->
		<!--		</dependency>-->
		<!--		<dependency>-->
		<!--			<groupId>io.springfox</groupId>-->
		<!--			<artifactId>springfox-swagger-ui</artifactId>-->
		<!--		</dependency>-->
		<dependency>
			<groupId>jakarta.jws</groupId>
			<artifactId>jakarta.jws-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec.jakarta.xml.ws</groupId>
			<artifactId>jboss-jakarta-xml-ws-api_4.0_spec</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-inline</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- SLF4J Simple Binding (for simple console output) -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.immutables</groupId>
			<artifactId>value</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>api</id>
			<!-- Dependencies for api documention generation -->
			<dependencies>
				<!-- Jakarta Persistence API (Replacement for javax.persistence) -->
				<dependency>
					<groupId>jakarta.persistence</groupId>
					<artifactId>jakarta.persistence-api</artifactId>
					<version>3.1.0</version>
				</dependency>

				<!-- Hibernate Core (Ensure compatibility with Jakarta
				Persistence API) -->
				<dependency>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-core</artifactId>
					<version>6.3.0.Final</version>
				</dependency>

				<!-- Jakarta XML Binding (Replacement for javax.xml.bind) -->
				<dependency>
					<groupId>jakarta.xml.bind</groupId>
					<artifactId>jakarta.xml.bind-api</artifactId>
					<version>3.0.1</version>
				</dependency>
				<dependency>
					<groupId>org.glassfish.jaxb</groupId>
					<artifactId>jaxb-runtime</artifactId>
					<version>3.0.1</version>
				</dependency>

				<!-- Jakarta Servlet API -->
				<dependency>
					<groupId>jakarta.servlet</groupId>
					<artifactId>jakarta.servlet-api</artifactId>
					<version>6.0.0</version>
				</dependency>

				<!-- Jakarta Faces API -->
				<dependency>
					<groupId>jakarta.faces</groupId>
					<artifactId>jakarta.faces-api</artifactId>
					<version>4.0.1</version>
				</dependency>

				<!-- Jakarta JMS API -->
				<dependency>
					<groupId>jakarta.jms</groupId>
					<artifactId>jakarta.jms-api</artifactId>
					<version>3.1.0</version>
				</dependency>

				<!-- Jakarta Concurrency API -->
				<dependency>
					<groupId>jakarta.enterprise.concurrent</groupId>
					<artifactId>jakarta.enterprise.concurrent-api</artifactId>
					<version>3.0.0</version>
				</dependency>

				<!-- Swagger Annotations -->
				<dependency>
					<groupId>io.swagger.core.v3</groupId>
					<artifactId>swagger-annotations</artifactId>
					<version>2.2.15</version>
				</dependency>

				<!-- Infinispan -->
				<dependency>
					<groupId>org.infinispan</groupId>
					<artifactId>infinispan-core</artifactId>
					<version>14.0.3.Final</version>
				</dependency>

				<dependency>
					<groupId>com.opencellsoft</groupId>
					<artifactId>opencell-model</artifactId>
					<version>${project.version}</version>
					<classifier>sources</classifier>
				</dependency>
				<dependency>
					<groupId>com.opencellsoft</groupId>
					<artifactId>opencell-admin-ejbs</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>com.opencellsoft</groupId>
					<artifactId>opencell-security</artifactId>
					<version>${project.version}</version>
					<classifier>sources</classifier>
				</dependency>
				<dependency>
					<groupId>com.opencellsoft</groupId>
					<artifactId>opencell-api-dto</artifactId>
					<version>${project.version}</version>
					<classifier>sources</classifier>
				</dependency>
				<dependency>
					<groupId>org.primefaces</groupId>
					<artifactId>primefaces</artifactId>
					<version>14.0.2</version>
				</dependency>
				<dependency>
					<groupId>com.thoughtworks.xstream</groupId>
					<artifactId>xstream</artifactId>
				</dependency>
				<dependency>
					<groupId>org.reflections</groupId>
					<artifactId>reflections</artifactId>
				</dependency>
				<dependency>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-core</artifactId>
					<version>2.20.0</version>
				</dependency>
				<dependency>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-api</artifactId>
					<version>2.20.0</version>
				</dependency>
				<dependency>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
					<version>3.2.2</version>
				</dependency>
				<dependency>
					<groupId>com.google.code.gson</groupId>
					<artifactId>gson</artifactId>
					<version>2.12.1</version>
				</dependency>
				<dependency>
					<groupId>org.apache.poi</groupId>
					<artifactId>poi</artifactId>
					<version>5.2.3</version>
				</dependency>

				<dependency>
					<groupId>com.googlecode.json-simple</groupId>
					<artifactId>json-simple</artifactId>
					<version>1.1.1</version>
				</dependency>
				<dependency>
					<groupId>com.github.spotbugs</groupId>
					<artifactId>spotbugs-annotations</artifactId>
					<version>4.7.3</version> <!-- Use the latest stable version -->
					<scope>provided</scope>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-clean-plugin</artifactId>
						<executions>
							<execution>
								<id>clean_docs</id>
								<phase>initialize</phase>
								<goals>
									<goal>clean</goal>
								</goals>
								<configuration>
									<excludeDefaultDirectories>true</excludeDefaultDirectories>
									<filesets>
										<fileset>
											<directory>
												${project.build.directory}/docs</directory>
										</fileset>
									</filesets>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>com.webcohesion.enunciate</groupId>
						<artifactId>enunciate-maven-plugin</artifactId>
						<executions>
							<execution>
								<phase>process-classes</phase>
								<goals>
									<goal>docs</goal>
								</goals>
								<configuration>
									<docsDir>${project.build.directory}/docs</docsDir>
									<configFile>src/main/resources/enunciate.xml</configFile>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>swagger</id>
			<dependencies>
				<dependency>
					<groupId>com.github.kongchen</groupId>
					<artifactId>swagger-maven-plugin</artifactId>
					<version>3.1.8</version>

				</dependency>
				<dependency>
					<groupId>com.github.javaparser</groupId>
					<artifactId>javaparser-symbol-solver-core</artifactId>
					<version>3.24.0</version> <!-- Use the latest version from
					Maven Central -->

				</dependency>
			</dependencies>
			<build>
				<plugins>
					<!--
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						    <version>3.1.0</version>

						<dependencies>
							<dependency>
								<groupId>com.github.javaparser</groupId>
								<artifactId>javaparser-symbol-solver-core</artifactId>
								            <version>3.24.0</version>

							</dependency>
						</dependencies>
						<executions>
							<execution>
								<phase>validate</phase>
								<goals>
									<goal>java</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<mainClass>org.meveo.api.ParserSwagger</mainClass>
							        <classpathScope>runtime</classpathScope>

						</configuration>
					</plugin>
					-->
					<plugin>
						<groupId>com.github.kongchen</groupId>
						<artifactId>swagger-maven-plugin</artifactId>
						<version>3.1.8</version>

						<dependencies>

							<dependency>
								<groupId>io.swagger.core.v3</groupId>
								<artifactId>swagger-jaxrs2</artifactId>
								<version>2.2.8</version>
							</dependency>

							<dependency>
								<groupId>jakarta.xml.bind</groupId>
								<artifactId>jakarta.xml.bind-api</artifactId>
								<version>4.0.0</version>
							</dependency>
							<dependency>
								<groupId>org.glassfish.jaxb</groupId>
								<artifactId>jaxb-runtime</artifactId>
								<version>4.0.0</version>
							</dependency>
							<dependency>
								<groupId>com.opencellsoft</groupId>
								<artifactId>opencell-model</artifactId>
								<classifier>sources</classifier>
							</dependency>
							<dependency>
								<groupId>com.opencellsoft</groupId>
								<artifactId>opencell-api-dto</artifactId>
								<classifier>sources</classifier>
							</dependency>
							<dependency>
								<groupId>com.opencellsoft</groupId>
								<artifactId>opencell-api</artifactId>
								<classifier>sources</classifier>
							</dependency>
							<dependency>
								<groupId>com.opencellsoft</groupId>
								<artifactId>opencell-admin-ejbs</artifactId>
								<classifier>sources</classifier>
							</dependency>
							<!--	
							<dependency>
								<groupId>javax.servlet</groupId>
								<artifactId>servlet-api</artifactId>
								<version>4.0.1</version>
								<scope>compile</scope>
							</dependency>
							
							<dependency>
								<groupId>org.jboss.resteasy</groupId>
								<artifactId>resteasy-multipart-provider</artifactId>
								<version>4.7.6.Final</version>
								<scope>compile</scope>
							</dependency>
							<dependency>
								<groupId>com.github.javaparser</groupId>
								<artifactId>javaparser-symbol-solver-core</artifactId>
								<version>3.24.2</version>
							</dependency>
							-->
						</dependencies>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>generate</goal>
								</goals>
								<configuration>
									<apiSources>
										<apiSource>
											<springmvc>false</springmvc>
											<locations>
												<location>org.meveo.api.rest</location>
												<location>org.meveo.apiv2</location>
											</locations>

											<schemes>http</schemes>
											<host>localhost:8080</host>
											<basePath>/api</basePath>
											<info>
												<title>OpenCell API</title>
												<version>1.0.0</version>
												<description>API Documentation
													for OpenCell</description>
											</info>
											<outputFormats>json,yaml</outputFormats>
											<outputPath>
												${project.build.directory}/swagger</outputPath>
										</apiSource>
									</apiSources>
									<swaggerConfig>
										<servers>
											<server>
												<url>${swagger.server.link}</url>
												<description>Server to test</description>
											</server>
										</servers>
										<info>
											<title>Swagger of Opencellsoft Api</title>
											<version>${project.version}</version>
											<contact>
												<email>contact@opencellsoft.fr</email>
												<name>OpenCellSoft</name>
												<url>
													https://opencellsoft.com/contact_us/</url>
											</contact>
											<license>
												<url>https://opencellsoft.com/</url>
												<name>Opencellsoft</name>
											</license>
											<description>@#Introduction</description>
										</info>
									</swaggerConfig>
									<resourcePackages>
										<resourcePackage>org.meveo.api.rest</resourcePackage>
									</resourcePackages>
									<outputDirectory>
										${project.build.directory}/generated-sources/swagger</outputDirectory>
									<outputFilename>swagger</outputFilename>
									<outputFormats>JSON,YAML</outputFormats>
									<prettyPrint>true</prettyPrint>
									<useResourcePackagesChildren>true</useResourcePackagesChildren>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>mdmodification</id>
			<dependencies>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<dependencies>
						</dependencies>
						<executions>
							<execution>
								<phase>validate</phase>
								<goals>
									<goal>java</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<mainClass>org.meveo.api.MdSwaggerModification</mainClass>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>