@full
Feature: Inherited CF in Account

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                                    | title                   | dto                    | api                                                            | action         | statusCode | status  | errorCode | message | entity          | expected                                                                                                 |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-cft-for-cust.json     | Create CFT for CUST     | CustomFieldTemplateDto | /entityCustomization/field/createOrUpdate                      | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-cft-for-ba.json       | Create CFT for BA       | CustomFieldTemplateDto | /entityCustomization/field/createOrUpdate                      | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-cft-for-ca.json       | Create CFT for CA       | CustomFieldTemplateDto | /entityCustomization/field/createOrUpdate                      | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-cft-for-ua.json       | Create CFT for UA       | CustomFieldTemplateDto | /entityCustomization/field/createOrUpdate                      | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-accountHierarchy.json | Create AccountHierarchy |                        | /account/accountHierarchy/createOrUpdate                       | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-customer.json         | Create customer         | CustomerDto            | /account/customer/createOrUpdate                               | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-customerAccount.json  | Create customer account | CustomerAccountDto     | /account/customerAccount/createOrUpdate                        | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-billingAccount.json   | Create billing account  | BillingAccountDto      | /account/billingAccount/createOrUpdate                         | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/create-userAccount.json      | Create user account     | UserAccountDto         | /account/userAccount/createOrUpdate                            | CreateOrUpdate |        200 | SUCCESS |           |         |                 |                                                                                                          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/find-customerAccount.json    | Find customer account   |                        | /account/customerAccount?customerAccountCode=RS_FULL_432_CUST1 | GET            |        200 | SUCCESS |           |         | customerAccount | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/find-customerAccount.json |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/find-billingAccount.json     | Find billing account    |                        | /account/billingAccount?billingAccountCode=RS_FULL_432_CUST1   | GET            |        200 | SUCCESS |           |         | billingAccount  | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/find-billingAccount.json  |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/find-userAccount.json        | Find user account       |                        | /account/userAccount?userAccountCode=RS_FULL_432_CUST1         | GET            |        200 | SUCCESS |           |         | userAccount     | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/find-userAccount.json     |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/delete-userAccount.json      | Delete User Account     |                        | /account/userAccount/RS_FULL_432_CUST1                                  | DEL            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/delete-billingAccount.json   | Delete Billing Account  |                        | /account/billingAccount/RS_FULL_432_CUST1                               | DEL            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/delete-customerAccount.json  | Delete CustomerAccount  |                        | /account/customerAccount/RS_FULL_432_CUST1                              | DEL            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/delete-customer.json         | Delete Customer         |                        | /account/customer/RS_FULL_432_CUST1                                     | DEL            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/remove-cft-ua.json           | Remove CFT UA           |                        | /entityCustomization/field/RS_FULL_ACCOUNT_CF_INHERITED/UserAccount     | DEL            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/remove-cft-ba.json           | Remove CFT BA           |                        | /entityCustomization/field/RS_FULL_ACCOUNT_CF_INHERITED/BillingAccount  | DEL            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/remove-cft-ca.json           | Remove CFT CA           |                        | /entityCustomization/field/RS_FULL_ACCOUNT_CF_INHERITED/CustomerAccount | DEL            |        200 | SUCCESS |           |         |        |          |
      | scenarios/full/00005-subscription-with-inherited-cf/02-inherited-cf-in-account/remove-cft-cust.json         | Remove CFT CUST         |                        | /entityCustomization/field/RS_FULL_ACCOUNT_CF_INHERITED/Customer        | DEL            |        200 | SUCCESS |           |         |        |          |
