@full
Feature: Entity Security - Cleanup Data

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                 | title                            | dto     | api                                              | action | statusCode | status  | errorCode                        | message                                               | entity | expected |
      | scenarios/full/00009-entity-security/09-cleanup-data/set-securedEntities-false.json      | Set securedEntities=false        |         | /                                                |        |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-customer-CUSTA.json          | Delete Customer CUSTA            |         | /account/customer/RS_FULL_18_CUSTA               | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/find-deleted-customer-CUSTA.json    | Find Deleted Customer CUSTA      |         | /account/customer?customerCode=RS_FULL_18_CUSTA  | GET    |        404 | FAIL    | ENTITY_DOES_NOT_EXISTS_EXCEPTION | Customer with code=RS_FULL_18_CUSTA does not exists.  |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-customer-CUSTB.json          | Delete Customer CUSTB            |         | /account/customer/RS_FULL_18_CUSTB               | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/find-deleted-customer-CUSTB.json    | Find Deleted Customer CUSTB      |         | /account/customer?customerCode=RS_FULL_18_CUSTB  | GET    |        404 | FAIL    | ENTITY_DOES_NOT_EXISTS_EXCEPTION | Customer with code=RS_FULL_18_CUSTB does not exists.  |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/remove-offerTemplate-no_seller.json | Remove offerTemplate - no seller |         | /catalog/offerTemplate/RS_FULL_18_OFFER_NOSELLER | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/remove-offerTemplate-A.json         | Remove offerTemplate - A         |         | /catalog/offerTemplate/RS_FULL_18_OFFER_SELLER_A | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/remove-offerTemplate-B.json         | Remove offerTemplate - B         |         | /catalog/offerTemplate/RS_FULL_18_OFFER_SELLER_B | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/remove-offerTemplate-C.json         | Remove offerTemplate - C         |         | /catalog/offerTemplate/RS_FULL_18_OFFER_SELLER_C | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/remove-offerTemplate-D.json         | Remove offerTemplate - D         |         | /catalog/offerTemplate/RS_FULL_18_OFFER_SELLER_D | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-seller-SELLER_A.json         | Delete Seller SELLER_A           |         | /seller/RS_FULL_18_SELLER_A                      | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/find-deleted-seller-SELLER_A.json   | Find deleted Seller SELLER_A     |         | /seller?sellerCode=RS_FULL_18_SELLER_A           | GET    |        404 | FAIL    | ENTITY_DOES_NOT_EXISTS_EXCEPTION | Seller with code=RS_FULL_18_SELLER_A does not exists. |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-seller-SELLER_C.json         | Delete Seller SELLER_C           |         | /seller/RS_FULL_18_SELLER_C                      | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-seller-SELLER_B.json         | Delete Seller SELLER_B           |         | /seller/RS_FULL_18_SELLER_B                      | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/find-deleted-seller-SELLER_B.json   | Find deleted Seller SELLER_B     |         | /seller?sellerCode=RS_FULL_18_SELLER_B           | GET    |        404 | FAIL    | ENTITY_DOES_NOT_EXISTS_EXCEPTION | Seller with code=RS_FULL_18_SELLER_B does not exists. |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/restore-user-to-default.json        | Restore User to default          | UserDto | /user                                            | PUT    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-user-level_1.json            | Delete User level 1              |         | /user/RS_FULL_18_Username.Level1                 | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-user-level_2.json            | Delete User level 2              |         | /user/RS_FULL_18_Username.Level2                 | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-user-level_21.json           | Delete User level 2.1            |         | /user/RS_FULL_18_Username.Level21                | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-user-level_22.json           | Delete User level 2.2            |         | /user/RS_FULL_18_Username.Level22                | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/delete-user-level_3.json            | Delete User level 3              |         | /user/RS_FULL_18_Username.Level3                 | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
      | scenarios/full/00009-entity-security/09-cleanup-data/remove-UserHierarchyLevel_1.json    | Remove UserHierarchyLevel 1      |         | /hierarchy/userGroupLevel/RS_FULL_18_LEVEL_1     | DEL    |        200 | SUCCESS |                                  |                                                       |        |          |
