@full
Feature: Entity Security - Customer Tests

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                                   | title                                           | dto     | api                                                                            | action | statusCode | status  | errorCode                              | message                                  | entity    | expected                                                                                                   |
      | scenarios/full/00009-entity-security/03-customer-tests/restore-user-to-default_1.json                      | Restore User to default                         | UserDto | /user                                                                          | PUT    |        200 | SUCCESS |                                        |                                          |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTA.json                            | Find Customer CUSTA                             |         | /account/customer?customerCode=RS_FULL_18_CUSTA                                | GET    |        200 | SUCCESS |                                        |                                          | customer  | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTA.json                            |
      | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTB.json                            | Find Customer CUSTB                             |         | /account/customer?customerCode=RS_FULL_18_CUSTB                                | GET    |        200 | SUCCESS |                                        |                                          | customer  | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTB.json                            |
      | scenarios/full/00009-entity-security/03-customer-tests/update-user-to-allow-access-to-CUSTA-only.json      | Update User to Allow Access to CUSTA only       | UserDto | /user                                                                          | PUT    |        200 | SUCCESS |                                        |                                          |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTA-still-accessible.json           | Find Customer CUSTA still accessible            |         | /account/customer?customerCode=RS_FULL_18_CUSTA                                | GET    |        200 | SUCCESS |                                        |                                          | customer  | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTA-still-accessible.json           |
      | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTB-not-accessible.json             | Find Customer CUSTB not accessible              |         | /account/customer?customerCode=RS_FULL_18_CUSTB                                | GET    |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTA-is-accessible.json  | List Customer with Filter CUSTA is accessible   |         | /account/customer/list?query=code:RS_FULL_18_CUSTA\|seller:RS_FULL_18_SELLER_A | GET    |        200 | SUCCESS |                                        |                                          | customers | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTA-is-accessible.json  |
      | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTB-not-accessible.json | List Customer with Filter CUSTB not accessible. |         | /account/customer/list?query=code:RS_FULL_18_CUSTB\|seller:RS_FULL_18_SELLER_B | GET    |        200 | SUCCESS |                                        |                                          | customers | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTB-not-accessible.json |
      | scenarios/full/00009-entity-security/03-customer-tests/find-seller-SELLER_A-not-accessible.json            | Find Seller SELLER_A not accessible             |         | /seller?sellerCode=RS_FULL_18_SELLER_A                                         | GET    |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/find-seller-SELLER_B-not-accessible.json            | Find Seller SELLER_B not accessible             |         | /seller?sellerCode=RS_FULL_18_SELLER_B                                         | GET    |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/update-user-to-allow-access-to-CUSTB-only.json      | Update User to Allow Access to CUSTB only       | UserDto | /user                                                                          | PUT    |        200 | SUCCESS |                                        |                                          |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTA-not-accessible.json             | Find Customer CUSTA not accessible              |         | /account/customer?customerCode=RS_FULL_18_CUSTA                                | GET    |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTB-now-accessible.json             | Find Customer CUSTB now accessible              |         | /account/customer?customerCode=RS_FULL_18_CUSTB                                | GET    |        200 | SUCCESS |                                        |                                          | customer  | scenarios/full/00009-entity-security/03-customer-tests/find-customer-CUSTB-now-accessible.json             |
      | scenarios/full/00009-entity-security/03-customer-tests/find-seller-SELLER_A-still-not-accessible.json      | Find Seller SELLER_A still not accessible       |         | /seller?sellerCode=RS_FULL_18_SELLER_A                                         | GET    |        200 | SUCCESS |                                        |                                          |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/find-seller-SELLER_B-still-not-accessible.json      | Find Seller SELLER_B still not accessible       |         | /seller?sellerCode=RS_FULL_18_SELLER_B                                         | GET    |        200 | SUCCESS |                                        |                                          |           |                                                                                                            |
      | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTA-not-accessible.json | List Customer with Filter CUSTA not accessible. |         | /account/customer/list?query=code:RS_FULL_18_CUSTA\|seller:RS_FULL_18_SELLER_A | GET    |        200 | SUCCESS |                                        |                                          | customers | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTA-not-accessible.json |
      | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTB-is-accessible.json  | List Customer with Filter CUSTB is accessible   |         | /account/customer/list?query=code:RS_FULL_18_CUSTB\|seller:RS_FULL_18_SELLER_B | GET    |        200 | SUCCESS |                                        |                                          | customers | scenarios/full/00009-entity-security/03-customer-tests/list-customer-with-filter-CUSTB-is-accessible.json  |
      | scenarios/full/00009-entity-security/03-customer-tests/restore-user-to-default_2.json                      | Restore User to default.                        |         | /                                                                              | PUT    |        200 | SUCCESS |                                        |                                          |           |                                                                                                            |
