@full @test
Feature: Entity Security - Seller Tests

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                               | title                                        | dto     | api                                    | action | statusCode | status  | errorCode                              | message                                  | entity | expected                                                                                          |
      | scenarios/full/00009-entity-security/02-seller-tests/restore-user-to-default_1.json                    | Restore User to default                      | UserDto | /user                                  | PUT    |        200 | SUCCESS |                                        |                                          |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_A.json                         | Find Seller SELLER_A                         |         | /seller?sellerCode=RS_FULL_15_SELLER_A | GET    |        200 | SUCCESS |                                        |                                          | seller | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_A.json                    |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_B.json                         | Find Seller SELLER_B                         |         | /seller?sellerCode=RS_FULL_15_SELLER_B | GET    |        200 | SUCCESS |                                        |                                          | seller | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_B.json                    |
      | scenarios/full/00009-entity-security/02-seller-tests/update-user-to-allow-access-to-MAIN_SELLER.json   | Update User to Allow Access to MAIN_SELLER   | UserDto | /user                                  | PUT    |        200 | SUCCESS |                                        |                                          |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_A-still-accessible_1.json      | Find Seller SELLER_A still accessible        |         | /seller?sellerCode=RS_FULL_15_SELLER_A | GET    |        200 | SUCCESS |                                        |                                          | seller | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_A-still-accessible_1.json |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_B-still-accessible.json        | Find Seller SELLER_B still accessible        |         | /seller?sellerCode=RS_FULL_15_SELLER_B | GET    |        200 | SUCCESS |                                        |                                          | seller | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_B-still-accessible.json   |
      | scenarios/full/00009-entity-security/02-seller-tests/update-user-to-allow-access-to-SELLER_A-only.json | Update User to Allow Access to SELLER_A only | UserDto | /user                                  | PUT    |        200 | SUCCESS |                                        |                                          |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_A-still-accessible_2.json      | Find Seller SELLER_A still accessible.       |         | /seller?sellerCode=RS_FULL_15_SELLER_A | GET    |        200 | SUCCESS |                                        |                                          | seller | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_A-still-accessible_2.json |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_B-not-accessible.json          | Find Seller SELLER_B not accessible          |         | /seller?sellerCode=RS_FULL_15_SELLER_B | GET    |        200 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-MAIN_SELLER-not-accessible.json       | Find Seller MAIN_SELLER not accessible       |         | /seller?sellerCode=MAIN_SELLER         | GET    |        200 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/update-user-to-allow-access-to-SELLER_B-only.json | Update User to Allow Access to SELLER_B only | UserDto | /user                                  | PUT    |        200 | SUCCESS |                                        |                                          |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_A-not-accessible.json          | Find Seller SELLER_A not accessible          |         | /seller?sellerCode=RS_FULL_15_SELLER_A | GET    |        200 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-SELLER_B-now-accessible.json          | Find Seller SELLER_B now accessible          |         | /seller?sellerCode=RS_FULL_15_SELLER_B | GET    |        200 | SUCCESS |                                        |                                          |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/find-seller-MAIN_SELLER-still-not-accessible.json | Find Seller MAIN_SELLER still not accessible |         | /seller?sellerCode=MAIN_SELLER         | GET    |        200 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |        |                                                                                                   |
      | scenarios/full/00009-entity-security/02-seller-tests/restore-user-to-default_2.json                    | Restore User to default.                     | UserDto | /user                                  | PUT    |        200 | SUCCESS |                                        |                                          |        |                                                                                                   |
