@full @test
Feature: Entity Security - AccountHierarchy API Tests

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                                             | title                                           | dto                    | api                                                 | action | statusCode | status  | errorCode                              | message                                  | entity   | expected                                                                                         |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/restore-user-to-default.json                      | Restore User to default                         | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_A-only.json | Update User to Allow Access to SELLER_A only    | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/create-CRMAccountHierarchy-fail.json              | Create CRMAccountHierarchy fail                 | CRMAccountHierarchyDto | /account/accountHierarchy/createCRMAccountHierarchy | POST   |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_B-only.json | Update User to Allow Access to SELLER_B only    | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/create-CRMAccountHierarchy.json                   | Create CRMAccountHierarchy                      | CRMAccountHierarchyDto | /account/accountHierarchy/createCRMAccountHierarchy | POST   |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_A-only.json | Update User to Allow Access to SELLER_A only.   | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/find-CRMAccountHierarchy.json                     | Find CRMAccountHierarchy fail                   |                        | /account/customer?customerCode=RS_FULL_15_CRM-CUST  | GET    |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_B-only.json | Update User to Allow Access to SELLER_B only.   | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/find-CRMAccountHierarchy.json                     | Find CRMAccountHierarchy.                       |                        | /account/customer?customerCode=RS_FULL_15_CRM-CUST  | GET    |        200 | SUCCESS |                                        |                                          | customer | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/find-CRMAccountHierarchy.json |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_A-only.json | Update User to Allow Access to SELLER_A only..  | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-CRMAccountHierarchy-fail.json              | Update CRMAccountHierarchy fail                 |                        | /account/accountHierarchy/updateCRMAccountHierarchy | POST   |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_B-only.json | Update User to Allow Access to SELLER_B only..  | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-CRMAccountHierarchy_1.json                 | Update CRMAccountHierarchy                      | CRMAccountHierarchyDto | /account/accountHierarchy/updateCRMAccountHierarchy | POST   |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_A-only.json | Update User to Allow Access to SELLER_A only... | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/find-CRMAccountHierarchy.json                     | Find CRMAccountHierarchy fail.                  |                        | /account/customer?customerCode=RS_FULL_15_CRM-CUST  | GET    |        401 | FAIL    | AUTHENTICATION_AUTHORIZATION_EXCEPTION | Access to entity details is not allowed. |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-SELLER_B-only.json | Update User to Allow Access to SELLER_B only... | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/find-CRMAccountHierarchy.json                     | Find CRMAccountHierarchy..                      |                        | /account/customer?customerCode=RS_FULL_15_CRM-CUST  | GET    |        200 | SUCCESS |                                        |                                          | customer | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/find-CRMAccountHierarchy.json |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-user-to-allow-access-to-CRM_CUST-only.json | Update User to Allow Access to CRM-CUST only    | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/update-CRMAccountHierarchy_2.json                 | Update CRMAccountHierarchy.                     |                        | /account/accountHierarchy/updateCRMAccountHierarchy | POST   |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/delete-customer-CRM_CUST.json                     | Delete Customer CRM_CUST                        |                        | /account/customer/RS_FULL_15_CRM-CUST               | DEL    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
      | scenarios/full/00009-entity-security/07-accountHierarchy-api-tests/restore-user-to-default.json                      | Restore User to default                         | UserDto                | /user                                               | PUT    |        200 | SUCCESS |                                        |                                          |          |                                                                                                  |
