<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"
>
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>opencell-admin</artifactId>
		<groupId>com.opencellsoft</groupId>
		<relativePath>../pom.xml</relativePath>
		<version>17.0.0</version>
	</parent>
	<artifactId>opencell-admin-web</artifactId>
	<name>Opencell Admin Web Application - Web Module</name>
	<packaging>war</packaging>
	<build>
		<finalName>opencell</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<excludes>
					<exclude>**/import-*.sql</exclude>
					<exclude>**/jasper/**/*</exclude>
					<exclude>**/invoiceAdjustment/**/*</exclude>
				</excludes>
				<filtering>true</filtering>
			</resource>
			<resource>
				<directory>src/main/resources/jasper</directory>
				<includes>
					<include>**/*</include>
				</includes>
				<targetPath>./jasper</targetPath>
				<filtering>false</filtering>
			</resource>
			<resource>
				<directory>src/main/resources/invoiceAdjustment</directory>
				<includes>
					<include>**/*</include>
				</includes>
				<targetPath>./invoiceAdjustment</targetPath>
				<filtering>false</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<!--do not upgrade, needed for maven-replacer -->
				<version>2.0.1</version>
				<configuration>
					<packagingExcludes>**/import*.sql</packagingExcludes>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<archive>
						<manifestFile>src/main/resources/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
				<executions>
					<execution>
						<id>prepare-war</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>exploded</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>
					<shortRevisionLength>41</shortRevisionLength>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<id>prepare-package</id>
						<phase>prepare-package</phase>
						<configuration>
							<target>
								<copy
									file="src/main/resources/import-${dbtype}.sql"
									tofile="${project.build.directory}/opencell/WEB-INF/classes/import.sql" />
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
					<execution>
						<id>install</id>
						<phase>install</phase>
						<configuration>
							<target>
								<copy
									file="../lib/opencell-sms-twilioModule.jar"
									tofile="${project.build.directory}/opencell/WEB-INF/lib/opencell-sms-twilioModule.jar" />
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!-- SWAGGER UI -->
			<!--			<plugin>-->
			<!--				<groupId>com.googlecode.maven-download-plugin</groupId>-->
			<!--				<artifactId>download-maven-plugin</artifactId>-->
			<!--				<version>1.9.0</version>-->
			<!--				<executions>-->
			<!--					<execution>-->
			<!--						<id>swagger-ui</id>-->
			<!--						<phase>prepare-package</phase>-->
			<!--						<goals>-->
			<!--							<goal>wget</goal>-->
			<!--						</goals>-->
			<!--						<configuration>-->
			<!--							<skipCache>false</skipCache>-->
			<!--							<url>-->
			<!--
			https://github.com/swagger-api/swagger-ui/archive/master.tar.gz</url>-->
			<!--							<unpack>true</unpack>-->
			<!--							<outputDirectory>./target</outputDirectory>-->
			<!--						</configuration>-->
			<!--					</execution>-->
			<!--				</executions>-->
			<!--			</plugin>-->
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-resources-apiv0</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>./target/opencell/pages/docs/v0</outputDirectory>
							<resources>
								<resource>
									<directory>./target/swagger-ui-master/dist</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
					<execution>
						<id>copy-resources-apiv1</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>./target/opencell/pages/docs/v1</outputDirectory>
							<resources>
								<resource>
									<directory>./target/swagger-ui-master/dist</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
					<execution>
						<id>copy-resources-apiv2</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>./target/opencell/pages/docs/v2</outputDirectory>
							<resources>
								<resource>
									<directory>./target/swagger-ui-master/dist</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.google.code.maven-replacer-plugin</groupId>
				<artifactId>replacer</artifactId>
				<executions>
					<execution>
						<id>apiv0</id>
						<goals>
							<goal>replace</goal>
						</goals>
						<phase>verify</phase>
						<configuration>
							<includes>
								<include>
									${project.build.directory}/opencell/pages/docs/v0/*</include>
							</includes>
							<replacements>
								<replacement>
									<token>
										https://petstore.swagger.io/v2/swagger.json</token>
									<value>/opencell/api/rest/v0/openapi.json</value>
								</replacement>
							</replacements>
						</configuration>
					</execution>
					<execution>
						<id>replace-version-location</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>replace</goal>
						</goals>
					</execution>
					<execution>
						<id>replace-swagger-json-location</id>
						<phase>verify</phase>
						<goals>
							<goal>replace</goal>
						</goals>
					</execution>
					<execution>
						<id>apiv1</id>
						<goals>
							<goal>replace</goal>
						</goals>
						<phase>verify</phase>
						<configuration>
							<includes>
								<include>
									${project.build.directory}/opencell/pages/docs/v1/*</include>
							</includes>
							<replacements>
								<replacement>
									<token>
										https://petstore.swagger.io/v2/swagger.json</token>
									<value>/opencell/api/rest/v1/openapi.json</value>
								</replacement>
							</replacements>
						</configuration>
					</execution>
					<execution>
						<id>apiv2</id>
						<goals>
							<goal>replace</goal>
						</goals>
						<phase>verify</phase>
						<configuration>
							<includes>
								<include>
									${project.build.directory}/opencell/pages/docs/v2/*</include>
							</includes>
							<replacements>
								<replacement>
									<token>
										https://petstore.swagger.io/v2/swagger.json</token>
									<value>/opencell/api/rest/v2/openapi.json</value>
								</replacement>
							</replacements>
						</configuration>
					</execution>
					<execution>
						<id>replace-version</id>
						<goals>
							<goal>replace</goal>
						</goals>
						<phase>prepare-package</phase>
						<configuration>
							<includes>
								<include>
									${project.build.directory}/opencell/layout/*.xhtml</include>
								<include>
									${project.build.directory}/opencell/about.xhtml</include>
								<include>
									${project.build.outputDirectory}/version.json</include>
							</includes>
							<replacements>
								<replacement>
									<token>@VERSION_NUMBER@</token>
									<value>${project.version}</value>
								</replacement>
								<replacement>
									<token>@BUILD_NUMBER@</token>
									<value>${buildNumber}</value>
								</replacement>
								<replacement>
									<token>@COMMIT_DATE@</token>
									<value>${commitDate}</value>
								</replacement>
							</replacements>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- SWAGGER UI -->
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-model</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-admin-ejbs</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-client</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-scripts</artifactId>
		</dependency>
		<dependency>
			<groupId>com.opencellsoft</groupId>
			<artifactId>opencell-custom-api</artifactId>
		</dependency>

		<dependency>
			<groupId>com.opencellsoft.wildfly</groupId>
			<artifactId>wildfly-cache-scripts</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- Libraries included in JBoss -->
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.ejb</groupId>
			<artifactId>jakarta.ejb-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec.jakarta.el</groupId>
			<artifactId>jboss-el-api_5.0_spec</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.faces</groupId>
			<artifactId>jakarta.faces-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.interceptor</groupId>
			<artifactId>jakarta.interceptor-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate.orm</groupId>
			<artifactId>hibernate-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.mail</groupId>
			<artifactId>jakarta.mail-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-core-jakarta</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-client</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- End of libraries included in Jboss -->
		<dependency>
			<groupId>org.omnifaces</groupId>
			<artifactId>omnifaces</artifactId>
		</dependency>
		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<classifier>jakarta</classifier>
		</dependency>
		<dependency>
			<groupId>org.primefaces.extensions</groupId>
			<artifactId>primefaces-extensions</artifactId>
			<classifier>jakarta</classifier>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-collections</groupId>
			<artifactId>commons-collections</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<!-- Use compile scope to avoid compilation error in Opencell
				Script, even if we add it to jboss-deployment-structure.xml -->
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.tika</groupId>
			<artifactId>tika-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>development</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<property>
					<name>env</name>
					<value>dev</value>
				</property>
			</activation>
		</profile>
		<profile>
			<id>integration</id>
			<activation>
				<property>
					<name>env</name>
					<value>integr</value>
				</property>
			</activation>
		</profile>
		<profile>
			<id>production</id>
			<activation>
				<property>
					<name>env</name>
					<value>prod</value>
				</property>
			</activation>
		</profile>
		<profile>
			<id>war-flavor</id>
			<activation>
				<property>
					<name>flavor</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-war-plugin</artifactId>
						<!--do not upgrade, needed for maven-replacer -->
						<version>2.0.1</version>
						<configuration>
							<classifier>${flavor}</classifier>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>