//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.30 at 08:09:14 AM CST 
//


package org.meveo.asg.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PricePlanEventData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricePlanEventData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PricePlanId" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="OrganizationId" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="RecurringCharge" type="{}RecurringChargeData" minOccurs="0"/>
 *         &lt;element name="UsageCharge" type="{}UsageChargeData" minOccurs="0"/>
 *         &lt;element name="SubscriptionFee" type="{}SubscriptionChargeData" minOccurs="0"/>
 *         &lt;element name="TerminationFee" type="{}TerminationChargeData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricePlanEventData", propOrder = {
    "pricePlanId",
    "organizationId",
    "recurringCharge",
    "usageCharge",
    "subscriptionFee",
    "terminationFee"
})
public class PricePlanEventData {

    @XmlElement(name = "PricePlanId", required = true)
    protected String pricePlanId;
    @XmlElement(name = "OrganizationId", required = true)
    protected String organizationId;
    @XmlElement(name = "RecurringCharge")
    protected RecurringChargeData recurringCharge;
    @XmlElement(name = "UsageCharge")
    protected UsageChargeData usageCharge;
    @XmlElement(name = "SubscriptionFee")
    protected SubscriptionChargeData subscriptionFee;
    @XmlElement(name = "TerminationFee")
    protected TerminationChargeData terminationFee;

    /**
     * Gets the value of the pricePlanId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricePlanId() {
        return pricePlanId;
    }

    /**
     * Sets the value of the pricePlanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricePlanId(String value) {
        this.pricePlanId = value;
    }

    /**
     * Gets the value of the organizationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * Sets the value of the organizationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationId(String value) {
        this.organizationId = value;
    }

    /**
     * Gets the value of the recurringCharge property.
     * 
     * @return
     *     possible object is
     *     {@link RecurringChargeData }
     *     
     */
    public RecurringChargeData getRecurringCharge() {
        return recurringCharge;
    }

    /**
     * Sets the value of the recurringCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecurringChargeData }
     *     
     */
    public void setRecurringCharge(RecurringChargeData value) {
        this.recurringCharge = value;
    }

    /**
     * Gets the value of the usageCharge property.
     * 
     * @return
     *     possible object is
     *     {@link UsageChargeData }
     *     
     */
    public UsageChargeData getUsageCharge() {
        return usageCharge;
    }

    /**
     * Sets the value of the usageCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageChargeData }
     *     
     */
    public void setUsageCharge(UsageChargeData value) {
        this.usageCharge = value;
    }

    /**
     * Gets the value of the subscriptionFee property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionChargeData }
     *     
     */
    public SubscriptionChargeData getSubscriptionFee() {
        return subscriptionFee;
    }

    /**
     * Sets the value of the subscriptionFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionChargeData }
     *     
     */
    public void setSubscriptionFee(SubscriptionChargeData value) {
        this.subscriptionFee = value;
    }

    /**
     * Gets the value of the terminationFee property.
     * 
     * @return
     *     possible object is
     *     {@link TerminationChargeData }
     *     
     */
    public TerminationChargeData getTerminationFee() {
        return terminationFee;
    }

    /**
     * Sets the value of the terminationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminationChargeData }
     *     
     */
    public void setTerminationFee(TerminationChargeData value) {
        this.terminationFee = value;
    }

}
