@full
Feature: Update service instance

  @admin
  Scenario Outline: <title>
    Given The entity has the following information "<jsonFile>" as "<dto>"
    When I call the "<action>" "<api>"
    Then Validate that the statusCode is "<statusCode>"
    And The status is "<status>"
    And The message  is "<message>"
    And The errorCode  is "<errorCode>"
    And The entity "<entity>" matches "<expected>"

    Examples: 
      | jsonFile                                                                                                            | title                                      | dto                        | api                                                                                                                       | action         | statusCode | status  | errorCode | message | entity       | expected                                                                                                     |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/create-CFT-serviceInstance.json               | Create CFT ServiceInstance                 | CustomFieldTemplateDto     | /entityCustomization/field/createOrUpdate                                                                                 | CreateOrUpdate |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/create-subscription.json                      | Create subscription                        | SubscriptionDto            | /billing/subscription                                                                                                     | Create         |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/activate-services.json                        | Activate services                          | ActivateServicesRequestDto | /billing/subscription/activateServices                                                                                    | POST           |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/find-subscription.json                        | Find subscription                          |                            | /billing/subscription?subscriptionCode=RS_FULL_164_SUB_UPD_SERV_100                                                       | GET            |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/update-services.json                          | Update services                            | UpdateServicesRequestDto   | /billing/subscription/updateServices                                                                                      | PUT            |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/find-subscription-updated.json                | Find subscription-Updated                  |                            | /billing/subscription?subscriptionCode=RS_FULL_164_SUB_UPD_SERV_100                                                       | GET            |        200 | SUCCESS |           |         | subscription | scenarios/full/00004-subscription-workflow/06-update-service-instance/find-subscription-updated.json         |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/update-services-change-quantity.json          | Update services - change quantity          | UpdateServicesRequestDto   | /billing/subscription/updateServices                                                                                      | PUT            |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/find-subscription-update-quantity.json        | Find subscription - Updated quantity       |                            | /billing/subscription?subscriptionCode=RS_FULL_164_SUB_UPD_SERV_100                                                       | GET            |        200 | SUCCESS |           |         | subscription | scenarios/full/00004-subscription-workflow/06-update-service-instance/find-subscription-update-quantity.json |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/delete-CFT-serviceInstance.json               | Delete CFT ServiceInstance                 |                            | /customFieldTemplate/RS_FULL_164_CF_SERV_UPD_100/ServiceInstance                                                          | DEL            |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/update-services-future-termination.json       | Update services - future termination       | UpdateServicesRequestDto   | /billing/subscription/updateServices                                                                                      | PUT            |        200 | SUCCESS |           |         |              |                                                                                                              |
      | scenarios/full/00004-subscription-workflow/06-update-service-instance/find-service-instance-future-termination.json | Find service instance - future termination |                            | /billing/subscription/serviceInstances?subscriptionCode=RS_FULL_164_SUB_UPD_SERV_100&serviceInstanceCode=RS_BASE_SERVICE1 | GET            |        200 | SUCCESS |           |         |              |                                                                                                              |
