//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.30 at 08:09:14 AM CST 
//


package org.meveo.asg.api.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriptionChargeData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionChargeData">
 *   &lt;complexContent>
 *     &lt;extension base="{}ChargeBaseData">
 *       &lt;sequence>
 *         &lt;element name="QuantityRangeCharges" type="{}ArrayOfQuantityRangeChargeData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionChargeData", propOrder = {
    "quantityRangeCharges"
})
public class SubscriptionChargeData
    extends ChargeBaseData
{

    @XmlElement(name = "QuantityRangeCharges")
    protected ArrayOfQuantityRangeChargeData quantityRangeCharges;

    /**
     * Gets the value of the quantityRangeCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfQuantityRangeChargeData }
     *     
     */
    public ArrayOfQuantityRangeChargeData getQuantityRangeCharges() {
        return quantityRangeCharges;
    }

    /**
     * Sets the value of the quantityRangeCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfQuantityRangeChargeData }
     *     
     */
    public void setQuantityRangeCharges(ArrayOfQuantityRangeChargeData value) {
        this.quantityRangeCharges = value;
    }

}
